//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Payrolls = new HashSet<Payroll>();
        }
    
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string Descriptions { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> PayrollAccountID { get; set; }
        public Nullable<int> PayrollID { get; set; }
        public Nullable<int> DiscountTypeId { get; set; }
        public Nullable<decimal> AmountAfterDiscount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payrolls { get; set; }
        public virtual PayrollAccount PayrollAccount { get; set; }
        public virtual Payroll Payroll { get; set; }
        public virtual DiscountType DiscountType { get; set; }
    }
}
