//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficiary()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int BeneficiaryID { get; set; }
        public string PatientCID { get; set; }
        public string CompanionCID { get; set; }
        public string BeneficiaryCID { get; set; }
        public string BeneficiaryFName { get; set; }
        public string BeneficiaryMName { get; set; }
        public string BeneficiaryLName { get; set; }
        public Nullable<int> BankID { get; set; }
        public string IBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
