//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        public int BonusID { get; set; }
        public decimal BasedSalary { get; set; }
        public Nullable<int> BonusTypeID { get; set; }
        public Nullable<int> BonusValue { get; set; }
        public Nullable<int> BonusFinalAmount { get; set; }
        public int EmployeeID { get; set; }
        public int PayAccountID { get; set; }
    
        public virtual BonuseType BonuseType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PayrollAccount PayrollAccount { get; set; }
    }
}
