//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetTransaction
    {
        public int ID { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<int> PayrollID { get; set; }
        public Nullable<int> DepositAccountID { get; set; }
    
        public virtual DepositAccount DepositAccount { get; set; }
        public virtual Payroll Payroll { get; set; }
    }
}
