//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepositAccount()
        {
            this.BudgetTransactions = new HashSet<BudgetTransaction>();
        }
    
        public int DepositID { get; set; }
        public string DepositTitle { get; set; }
        public System.DateTime DepositDate { get; set; }
        public int DepositTypeID { get; set; }
        public int DepositDepartmentID { get; set; }
        public int AgencyID { get; set; }
        public int PayeeID { get; set; }
        public string PayeeName { get; set; }
        public decimal AmountDeposited { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDare { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetTransaction> BudgetTransactions { get; set; }
        public virtual PayrollAccount PayrollAccount { get; set; }
        public virtual DepositType DepositType { get; set; }
        public virtual DepositDepartment DepositDepartment { get; set; }
        public virtual Payee Payee { get; set; }
    }
}
