//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInsurance
    {
        public int InsuranceID { get; set; }
        public decimal BasedSalary { get; set; }
        public Nullable<int> InsuranceTypeID { get; set; }
        public int InsuranceOptionID { get; set; }
        public int InsuranceAmount { get; set; }
        public int EmployeeID { get; set; }
        public int PayAccountID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual InsuranceType InsuranceType { get; set; }
        public virtual InsuranceOption InsuranceOption { get; set; }
        public virtual PayrollAccount PayrollAccount { get; set; }
    }
}
