//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAccountType
    {
        public int Id { get; set; }
        public int AgencyAccountID { get; set; }
        public int SalaryAccountID { get; set; }
        public string SalaryAccountDesc { get; set; }
        public int BonusAccountID { get; set; }
        public string BonusAccountDesc { get; set; }
        public int OvertimeAccountID { get; set; }
        public string OvertimeAccountDesc { get; set; }
        public int InsuranceAccountID { get; set; }
        public string InsuranceAccountDesc { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual AccountType AccountType1 { get; set; }
        public virtual AccountType AccountType2 { get; set; }
        public virtual AccountType AccountType3 { get; set; }
        public virtual AccountType AccountType4 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
