//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Overtime
    {
        public int OvertimeID { get; set; }
        public Nullable<decimal> BasedSalary { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
        public Nullable<int> RegularHours { get; set; }
        public Nullable<int> OvertimeHours { get; set; }
        public Nullable<decimal> CalculatedOverTimeAmount { get; set; }
        public int EmployeeID { get; set; }
        public int PayAccountID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PayrollAccount PayrollAccount { get; set; }
    }
}
