//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientExtension
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientExtension()
        {
            this.PatientExtensionHistories = new HashSet<PatientExtensionHistory>();
        }
    
        public int ExtensionId { get; set; }
        public string PatientCID { get; set; }
        public System.DateTime ExtensionStartDate { get; set; }
        public System.DateTime ExtensionEndDate { get; set; }
        public string ExtensionDocLink { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientExtensionHistory> PatientExtensionHistories { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
