//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientExtensionHistory
    {
        public int ExtensionHistoryId { get; set; }
        public int ExtensionId { get; set; }
        public string PatientCID { get; set; }
        public System.DateTime ExtensionStartDate { get; set; }
        public System.DateTime ExtensionEndDate { get; set; }
        public string ExtensionDocLink { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ExtensionCreatedDate { get; set; }
        public Nullable<System.DateTime> ExtensionModifiedDate { get; set; }
        public string ExtensionHistoryDocLink { get; set; }
        public string FileName { get; set; }
    
        public virtual PatientExtension PatientExtension { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
