//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientHistory
    {
        public int Id { get; set; }
        public string PatientCID { get; set; }
        public string PatientFName { get; set; }
        public string PatientMName { get; set; }
        public string PatientLName { get; set; }
        public string KWTphone { get; set; }
        public string USphone { get; set; }
        public Nullable<int> HospitalID { get; set; }
        public int DoctorID { get; set; }
        public int AgencyID { get; set; }
        public Nullable<int> BankID { get; set; }
        public string Iban { get; set; }
        public Nullable<System.DateTime> FirstApptDate { get; set; }
        public Nullable<System.DateTime> EndTreatDate { get; set; }
        public Nullable<bool> IsBeneficiary { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
        public System.DateTime OldCreatedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string PrimaryCompanionCid { get; set; }
    }
}
