//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payee()
        {
            this.Payrolls = new HashSet<Payroll>();
            this.DepositAccounts = new HashSet<DepositAccount>();
        }
    
        public int PayeeID { get; set; }
        public string PayeeName { get; set; }
        public string PayeeStreetAddress { get; set; }
        public string PayeeCity { get; set; }
        public string PayeeState { get; set; }
        public string PayeeZipcode { get; set; }
        public string PayeePhone { get; set; }
        public string PayeeEmail { get; set; }
        public string PayeeBankName { get; set; }
        public string PayeeBankAccount { get; set; }
        public string PayeeBankRoutingNumber { get; set; }
        public int PayeeTypeID { get; set; }
    
        public virtual PayeesType PayeesType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payroll> Payrolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositAccount> DepositAccounts { get; set; }
    }
}
