//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payroll()
        {
            this.CheckPayrolls = new HashSet<CheckPayroll>();
            this.WirePayrolls = new HashSet<WirePayroll>();
            this.Accounts = new HashSet<Account>();
            this.BudgetTransactions = new HashSet<BudgetTransaction>();
        }
    
        public int TransactionID { get; set; }
        public string TransactionIDFormat { get; set; }
        public int PayrollMethodId { get; set; }
        public int PayrollStatusID { get; set; }
        public int PayrollTypeID { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public Nullable<int> PayeeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string PayeeName { get; set; }
        public int PayeeTypeID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDueDate { get; set; }
        public System.DateTime PaymentCreatedDate { get; set; }
        public Nullable<int> WireNumber { get; set; }
        public Nullable<int> CheckNumber { get; set; }
        public string PaymentCreatedBy { get; set; }
        public string PaymentEnteredBy { get; set; }
        public System.DateTime PaymentEnteredDate { get; set; }
        public string PaymentApprovedBy { get; set; }
        public Nullable<System.DateTime> PaymentApprovedDate { get; set; }
        public string PaymentAuthorizedBy { get; set; }
        public Nullable<System.DateTime> PaymentAuthorizedDate { get; set; }
        public string PaymentPaidBy { get; set; }
        public Nullable<System.DateTime> PaymentPaidDate { get; set; }
        public string PaymentReconciledBy { get; set; }
        public Nullable<System.DateTime> PaymentReconciledDate { get; set; }
        public Nullable<System.DateTime> PaymentModifiedDate { get; set; }
        public string PaymentModifiedBy { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckPayroll> CheckPayrolls { get; set; }
        public virtual Payee Payee { get; set; }
        public virtual PayeesType PayeesType { get; set; }
        public virtual PayrollMethod PayrollMethod { get; set; }
        public virtual PayrollStatu PayrollStatu { get; set; }
        public virtual PayrollType PayrollType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WirePayroll> WirePayrolls { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetTransaction> BudgetTransactions { get; set; }
    }
}
