//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryDeduction
    {
        public int DeductionID { get; set; }
        public decimal BasedSalary { get; set; }
        public decimal HourlyRate { get; set; }
        public Nullable<int> DeductionPercentage { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public Nullable<int> DeductedHours { get; set; }
        public Nullable<int> DeductedDays { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
