//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryIncrement
    {
        public int Id { get; set; }
        public decimal IncrementAmount { get; set; }
        public int TitleID { get; set; }
    
        public virtual Title Title { get; set; }
    }
}
