//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kwt.PatientsMgtApp.PersistenceDB.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int EmployeeID { get; set; }
        public Nullable<decimal> Salary1 { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public decimal StartingSalary { get; set; }
        public Nullable<decimal> YearlySalaryIncrement { get; set; }
        public Nullable<int> TaxCategoryID { get; set; }
        public int PayAccountID { get; set; }
        public int SalaryID { get; set; }
        public Nullable<decimal> ExperienceSalary { get; set; }
        public Nullable<decimal> ExperienceWithInsuranceSalary { get; set; }
        public Nullable<decimal> ExperienceWithTaxSalary { get; set; }
        public Nullable<decimal> TotalSalary { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PayrollAccount PayrollAccount { get; set; }
        public virtual TaxCategory TaxCategory { get; set; }
    }
}
